version: '3.9'

services:
  python:
    image: "poetry-python:latest"
    container_name: 'poetry-python'
    user: ${USER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=${USER}
    volumes:
      - ./poetry/:/poetry/