[tool.poetry]
name = "main packages"
version = "1.3.5"
description = "poetry requirements creation"
authors = ["Dmitry Afanasyev <Balshbox@gmail.com>"]

[build-system]
requires = ["poetry-core>=1.7.1"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python=">=3.11,<3.12"
aiohttp = "^3.9"
aiosignal = "^1.3"
alembic = "^1.11"
bcrypt = "^4.0"
celery = "^5.3"
click = "^8.1"
cookiecutter = "^2.5"
decorator = "^5.1"
Django = "^4.2"
factory-boy = "^3.3"
Faker = "^19.0"
fastapi = "^0.104"
gunicorn = "^21.2"
httpx = "^0.25"
Jinja2 = "^3.1"
loguru = "^0.7"
MouseInfo = "0.1"
numpy = "^1.26"
orjson = "^3.9"
Pillow = "^10.0"
pre-commit = "^3.5"
prompt-toolkit = "^3.0"
psycopg2-binary = "^2.9.7"
PyAutoGUI = "^0.9"
pydantic = "^2.5"
Pygments = "^2.16"
pyinstaller = "^6.2"
PyQt6 = "^6.5"
python-decouple = "^3.8"
pytz = "^2023.3"
redis = {version = "^5.0", extras = ["asyncio"]}
requests = "^2.31"
selenium = "^4.14"
simple-term-menu = "^1.6"
six = "^1.16"
SQLAlchemy = "^2.0"
termcolor = "^2.3"
uvicorn = "^0.24"
validators = "^0.22"
virtualenv = "^20.24"
wget = "^3.2"
zipp = "^3.16"

[tool.poetry.dev-dependencies]
ipython = "^8.18"

black = "^23.11"
mypy = "^1.7"

autoflake = "^2.2"
flake8 = "^6.1"
flake8-logging-format = "^0.9"
flake8-comprehensions = "^3.14"
flake8-eradicate = "^1.5"
flake8-deprecated = "^2.0"
flake8-pytest-style = "^1.7"
flake8-aaa = "^0.17"
flake8-bugbear = "^23.11"
flake8-warnings = "^0.4"
flake8-debugger = "^4.1"
flake8-annotations-complexity = "^0.0.8"
flake8-fixme = "^1.1"
flake8-simplify = "^0.21"
flake8-variables-names = "^0.0.6"
flake8-bandit = "^4.1"
flake8-tidy-imports = "^4.10"
flake8-noqa = "^1.3"
flake8-useless-assert = "^0.4"
flake8-mock = "^0.4"
flake8-comments = "^0.1"
flake8-newspaper-style = "^0.4"
Flake8-pyproject = "^1.2.3"

pytest = "^7.4"
pytest-asyncio = "^0.21"
pytest-deadfixtures = "^2.2"
pytest-repeat = "^0.9"
pytest-testmon = "^2.1"
pytest-mock = "^3.12"
pytest-cov = "^4.1"
pytest-timeout = "^2.1"
pytest-timeouts = "^1.2"
pytest-sugar = "^0.9"
pytest-clarity = "^1.0"
pytest-env = "^1.1"
nest-asyncio = "^1.5"
pytest-html = "^4.1"
pytest-randomly = "^3.15"
pytest-split = "^0.8"
pytest-freezegun = "^0.4"
pytest-socket = "^0.6"
assertpy = "^1.1"
respx = "^0.20"

safety = "^2.4.0b2"
pip-audit = "^2.6"

ruff = "^0.1"
