[tool.poetry]
name = "main packages"
version = "1.0.2"
description = "poetry requiremts creation"
authors = ["Dmitry Afanasyev <Balshbox@gmail.com>"]

[tool.poetry.dependencies]
Python=">=3.11,<3.12"
aiohttp = "^3.8"
aiosignal = "^1.3"
alembic = "^1.11"
bcrypt = "^4.0"
celery = "^5.3"
click = "^8.1"
cookiecutter = "^2.3"
decorator = "^5.1"
Django = "^4.2"
factory-boy = "^3.3"
Faker = "^19.0"
fastapi = "^0.101"
gunicorn = "^21.2"
httpx = "^0.24"
Jinja2 = "^3.1"
loguru = "^0.7"
MouseInfo = "0.1"
numpy = "^1.25"
orjson = "^3.9"
Pillow = "^10.0"
pre-commit = "^3.3"
prompt-toolkit = "^3.0"
psycopg2-binary = "^2.9.7"
PyAutoGUI = "^0.9"
pydantic = "^2.3"
Pygments = "^2.16"
pyinstaller = "^5.13"
PyQt6 = "^6.5"
python-decouple = "^3.8"
pytz = "^2023.3"
redis = {version = "^5.0", extras = ["asyncio"]}
requests = "^2.31"
selenium = "^4.11"
simple-term-menu = "^1.6"
six = "^1.16"
SQLAlchemy = "^2.0"
SQLAlchemy-Utils = "^0.41"
termcolor = "^2.3"
uvicorn = "^0.23"
validators = "^0.21"
virtualenv = "^20.24"
wget = "^3.2"
zipp = "^3.16"

[tool.poetry.dev-dependencies]
ipython = "^8.14"

black = "^23.7"
mypy = "^1.5"
flake8 = "^6.1"
flake8-aaa = "^0.16"
flake8-variables-names = "^0.0.6"
flake8-deprecated = "^2.0"
flake8-noqa = "^1.3"
flake8-annotations-complexity = "^0.0.8"
autoflake = "2.2"
flake8-useless-assert = "^0.4"
flake8-warnings = "^0.4"
flake8-newspaper-style = "^0.4"
flake8-comments = "^0.1"
flake8-jira-todo-checker = "^0.6"
flake8-mock = "^0.4"

pytest = "^7.4"
pytest-cov = "^4.1"
pytest-repeat = "^0.9"
pytest-asyncio = "^0.21"
pytest-deadfixtures = "^2.2"
pytest-mock = "^3.11"
pytest-sugar = "^0.9"
pytest-clarity = "^1.0"
pytest-html = "^3.2"
pytest-timeouts = "^1.2"
pytest-randomly = "^3.15"
pytest-split = "^0.8"
pytest-freezegun = "^0.4"
pytest-socket = "^0.6"
assertpy = "^1.1"
coverage = "^7.3"

safety = "^2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
