[tool.poetry]
name = "create requirements"
version = "1.0.2"
description = "poetry requiremts creation"
authors = ["Dmitry Afanasyev <Balshbox@gmail.com>"]

[tool.poetry.dependencies]
Python="3.11.1"
aiohttp = "*"
aiosignal = "*"
alembic = "*"
bcrypt = "*"
click = "*"
cookiecutter = "*"
coverage = "*"
decorator = "*"
Django = "*"
factory-boy = "*"
Faker = "*"
fastapi = "*"
httpx = "*"
identify = "*"
Jinja2 = "*"
keyring = "*"
loguru = "*"
MouseInfo = "*"
numpy = "*"
orjson = "*"
Pillow = "*"
pre-commit = "*"
prompt-toolkit = "*"
psycopg2-binary = "*"
PyAutoGUI = "*"
pydantic = "*"
Pygments = "*"
PyQt6 = "*"
python-decouple = "*"
pytz = "*"
PyYAML = "*"
requests = "*"
selenium = "*"
simple-term-menu = "*"
six = "*"
SQLAlchemy = "*"
starlette = "*"
termcolor = "*"
uvicorn = "*"
validators = "*"
virtualenv = "*"
wget = "*"
zipp = "*"

[tool.poetry.dev-dependencies]
black = "*"
flake8 = "*"
ipython = "*"
mypy = "*"
pytest = "*"
pytest-cov = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
