name: test

on:
  push:
    branches-ignore:
      - test
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - 'release/**'

jobs:
  test-poetry:
    name: pyproject.toml check
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install poetry
        env:  # Keep in sync with `POETRY_VERSION` in `Dockerfile`
          POETRY_VERSION: "1.7.1"
        run: |
          curl -sSL "https://install.python-poetry.org" | python -
          # Adding `poetry` to `$PATH`:
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist for poetry check
      #----------------------------------------------
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-ansi --no-root
          poetry run pip install -U pip
      #----------------------------------------------
      #              check dependencies
      #----------------------------------------------
      - name: Extended checks
        continue-on-error: true
        run: |
          poetry run poetry check
          poetry run pip check
          poetry run safety check --full-report
          poetry run pip-audit

  test-docker:
    name: Docker build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check docker-compose
        env: # Keep in sync with `POETRY_VERSION` in `Dockerfile`
          POETRY_LOCK: "./poetry/poetry.lock"
          REQUIREMENTS: "./poetry/requirements.txt"
        run: |
          docker compose up --build
          bash if [ -f "$POETRYLOCK" ] && [ -f "$REQUIREMENTS" ]; then echo "poetry.lock and requirements.txt created successfully" exit 0 fi